version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - source ~/.bashrc
      - go get google.golang.org/protobuf/cmd/protoc-gen-go
      - protoc -I proto proto/server/server.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
